import * as path from "path";

export const PROJECT_ROOT = process.cwd();

const LOCAL_CODEBASE_DIRECTORY_NAME = "codebase";
export const LOCAL_CODEBASE_DIRECTORY_PATH = path.join(PROJECT_ROOT, LOCAL_CODEBASE_DIRECTORY_NAME);

const SCID_FOLDER_NAME = "SCID";
export const CODEBASE_SCID_FOLDER_PATH = path.join(LOCAL_CODEBASE_DIRECTORY_PATH, SCID_FOLDER_NAME);

export const TEST_SCID_FILE_NAME_START_PATTERN = "_testSCID";

export const CHECK_TYPES = {
  LINT_CHECKS: "CODE LINTS CHECK",
  COVERAGE_CHECKS: "UNIT TESTING AND IT'S CODE COVERAGE CHECK",
  LOCKED_FILE_MODIFICATION_CHECK: "LOCKED FILE MODIFICATION CHECK"
};
